import type { Opening } from "@/lib/building/geometry";
import type { HousePlan } from "@/lib/building/houseBuilder";

function stack(face: Opening["face"], along: number, floors: number[], kinds: Opening["kind"][]): Opening[] {
  return floors.map((floor, i) => ({ face, along, floor: floor as 0 | 1 | 2 | 3, kind: kinds[i] ?? "rect-shutter" }));
}

export const CASA_NARROW: HousePlan = {
  id: "narrow",
  name: "Casa del Vicolo",
  W: 7.2,
  D: 8.0,
  floors: 3,
  floorY: [0, 3.4, 6.55, 9.7],
  eaveY: 9.7,
  roofH: 2.6,
  overhang: 0.42,
  wallT: 0.34,
  brickSplit: 0.2,
  backBrickFrac: 0.42,
  stucco: "#dcc4a0",
  number: "25",
  mailbox: true,
  chimneys: [
    [-1.8, 1.1, 1.15],
    [1.9, -1.2, 1.05],
  ],
  openings: [
    ...stack("front", -1.9, [0, 1, 2], ["barred", "rect-shutter", "rect-shutter"]),
    { face: "front", along: 0.15, floor: 0, kind: "plank-arch" },
    ...stack("front", 2.05, [0, 1, 2], ["small", "rect-balcony", "rect-shutter"]),
    ...stack("left", 1.7, [0, 1, 2], ["barred", "rect-shutter", "rect-shutter"]),
    { face: "left", along: -2.0, floor: 0, kind: "rect-door" },
    { face: "left", along: -2.0, floor: 1, kind: "rect-shutter" },
    ...stack("right", 1.85, [0, 1, 2], ["barred", "rect-shutter", "rect-shutter"]),
    { face: "right", along: -1.9, floor: 0, kind: "barred" },
    { face: "right", along: -1.9, floor: 1, kind: "rect-balcony" },
    { face: "back", along: -1.8, floor: 0, kind: "barred" },
    { face: "back", along: 0, floor: 1, kind: "rect-shutter" },
    { face: "back", along: 1.9, floor: 0, kind: "rect-door" },
    { face: "back", along: 1.9, floor: 1, kind: "rect-shutter" },
    { face: "back", along: -1.8, floor: 2, kind: "small" },
    { face: "back", along: 1.9, floor: 2, kind: "rect-shutter" },
  ],
};

export const CASA_ROSA: HousePlan = {
  id: "rosa",
  name: "Casa Rosa",
  W: 8.4,
  D: 7.6,
  floors: 3,
  floorY: [0, 3.45, 6.6, 9.85],
  eaveY: 9.85,
  roofH: 2.7,
  overhang: 0.44,
  wallT: 0.35,
  brickSplit: 0.15,
  backBrickFrac: 0.3,
  stucco: "#e5c4b0",
  number: "9",
  mailbox: false,
  chimneys: [
    [-2.4, 0.9, 1.2],
    [0.2, -1.4, 1.1],
    [2.6, 1.0, 1.05],
  ],
  openings: [
    { face: "front", along: -2.4, floor: 0, kind: "barred" },
    { face: "front", along: 0, floor: 0, kind: "arch-door" },
    { face: "front", along: 2.4, floor: 0, kind: "small" },
    { face: "front", along: -2.4, floor: 1, kind: "rect-shutter" },
    { face: "front", along: 0, floor: 1, kind: "arch-balcony" },
    { face: "front", along: 2.4, floor: 1, kind: "rect-shutter" },
    { face: "front", along: -2.4, floor: 2, kind: "rect-shutter" },
    { face: "front", along: 0, floor: 2, kind: "rect-shutter" },
    { face: "front", along: 2.4, floor: 2, kind: "rect-shutter" },
    ...stack("left", 1.6, [0, 1, 2], ["barred", "rect-shutter", "rect-shutter"]),
    { face: "left", along: -1.8, floor: 0, kind: "rect-door" },
    { face: "left", along: -1.8, floor: 1, kind: "rect-balcony" },
    ...stack("right", 1.7, [0, 1, 2], ["small", "rect-shutter", "rect-shutter"]),
    { face: "right", along: -1.7, floor: 1, kind: "rect-shutter" },
    { face: "back", along: -2.2, floor: 0, kind: "barred" },
    { face: "back", along: 0.1, floor: 1, kind: "rect-shutter" },
    { face: "back", along: 2.2, floor: 0, kind: "rect-door" },
    { face: "back", along: -2.2, floor: 1, kind: "rect-shutter" },
    { face: "back", along: 2.2, floor: 1, kind: "rect-shutter" },
    { face: "back", along: -2.2, floor: 2, kind: "small" },
    { face: "back", along: 2.2, floor: 2, kind: "rect-shutter" },
  ],
};

export const CASA_FORNO: HousePlan = {
  id: "forno",
  name: "Casa del Forno",
  W: 6.6,
  D: 7.2,
  floors: 2,
  floorY: [0, 3.5, 6.7],
  eaveY: 6.7,
  roofH: 2.4,
  overhang: 0.4,
  wallT: 0.34,
  brickSplit: -0.4,
  backBrickFrac: 0.55,
  stucco: "#cfc0a2",
  number: "32",
  mailbox: false,
  chimneys: [[-1.4, -0.8, 1.25]],
  openings: [
    { face: "front", along: -1.7, floor: 0, kind: "barred" },
    { face: "front", along: 0.2, floor: 0, kind: "carriage" },
    { face: "front", along: 1.85, floor: 0, kind: "small" },
    { face: "front", along: -1.7, floor: 1, kind: "rect-shutter" },
    { face: "front", along: 0.2, floor: 1, kind: "rect-balcony" },
    { face: "front", along: 1.85, floor: 1, kind: "rect-shutter" },
    { face: "left", along: 1.4, floor: 0, kind: "barred" },
    { face: "left", along: 1.4, floor: 1, kind: "rect-shutter" },
    { face: "left", along: -1.6, floor: 0, kind: "rect-door" },
    { face: "right", along: 1.5, floor: 0, kind: "small" },
    { face: "right", along: 1.5, floor: 1, kind: "rect-shutter" },
    { face: "back", along: -1.6, floor: 0, kind: "barred" },
    { face: "back", along: 1.6, floor: 0, kind: "rect-door" },
    { face: "back", along: 0, floor: 1, kind: "rect-shutter" },
    { face: "back", along: 1.6, floor: 1, kind: "small" },
  ],
};

export const CASA_OPPOSITE: HousePlan = {
  id: "opposta",
  name: "Casa Opposta",
  W: 9.0,
  D: 8.0,
  floors: 3,
  floorY: [0, 3.42, 6.58, 9.8],
  eaveY: 9.8,
  roofH: 2.75,
  overhang: 0.44,
  wallT: 0.35,
  brickSplit: 0.25,
  backBrickFrac: 0.28,
  stucco: "#e8d8c4",
  number: "4",
  mailbox: true,
  chimneys: [
    [-2.6, 1.2, 1.15],
    [2.4, -1.1, 1.1],
  ],
  openings: [
    { face: "front", along: -2.6, floor: 0, kind: "barred" },
    { face: "front", along: 0, floor: 0, kind: "herringbone" },
    { face: "front", along: 2.6, floor: 0, kind: "small" },
    { face: "front", along: -2.6, floor: 1, kind: "rect-shutter" },
    { face: "front", along: 0, floor: 1, kind: "arch-balcony" },
    { face: "front", along: 2.6, floor: 1, kind: "rect-shutter" },
    { face: "front", along: -2.6, floor: 2, kind: "rect-shutter" },
    { face: "front", along: 0, floor: 2, kind: "rect-shutter" },
    { face: "front", along: 2.6, floor: 2, kind: "rect-shutter" },
    ...stack("left", 1.7, [0, 1, 2], ["barred", "rect-shutter", "rect-shutter"]),
    { face: "left", along: -1.9, floor: 0, kind: "rect-door" },
    { face: "left", along: -1.9, floor: 1, kind: "rect-balcony" },
    ...stack("right", 1.8, [0, 1, 2], ["barred", "rect-shutter", "rect-shutter"]),
    { face: "back", along: -2.4, floor: 0, kind: "barred" },
    { face: "back", along: 0, floor: 1, kind: "rect-shutter" },
    { face: "back", along: 2.4, floor: 0, kind: "rect-door" },
    { face: "back", along: -2.4, floor: 2, kind: "small" },
    { face: "back", along: 2.4, floor: 1, kind: "rect-shutter" },
    { face: "back", along: 2.4, floor: 2, kind: "rect-shutter" },
  ],
};

export const STREET_PLANS: { plan: HousePlan; position: [number, number, number]; yaw: number }[] = [
  { plan: CASA_NARROW, position: [-10.6, 0, 0.35], yaw: 0 },
  { plan: CASA_ROSA, position: [11.2, 0, 0.15], yaw: 0 },
  { plan: CASA_FORNO, position: [-4.4, 0, -18.6], yaw: 0 },
  { plan: CASA_OPPOSITE, position: [6.8, 0, -18.5], yaw: 0 },
];
